backend:
  name: git-gateway
  branch: main # Branch to update (your primary branch on GitHub)

publish_mode: editorial_workflow # Recommended for review process

media_folder: "static/uploads" # Where to upload images/media from the CMS
public_folder: "/static/uploads" # The public path to the media folder

collections:
  - name: "posts" # A label used in the CMS UI
    label: "Articles" # The name displayed in the CMS UI
    folder: "articles" # The path to the folder where content files will be stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Format of the filename
    fields: # The fields for each article
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", required: true}
      - {label: "Category", name: "category", widget: "string", required: true} # Consider adding a select widget with predefined options later
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Image Alt Text", name: "image_alt", widget: "string", required: false}
      - {label: "Summary", name: "summary", widget: "text", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
